#!/bin/bash
set -x

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE test LOGIN SUPERUSER PASSWORD 'postgres';
	CREATE DATABASE test;
	GRANT ALL PRIVILEGES ON DATABASE test TO test;
EOSQL